image: node:9.9

pipelines:
  default:
    - step:
        caches:
            - node
        script:
          - node --version
          - cp .env.example .env
          - yarn install
          - yarn build
